### ISSUE TITLE
Download plots! button yields unexpected/messy result

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/blobulator#385]
When I press "Download plots!" I expect potentially a zip file that has individual plots saved as pdf that I can import into my slide or manuscript. 

The current function is to prompt a print screen of all blobulator results, which can then be saved as a pdf. This pdf may have cut-off legend text and the sliders are invisible (see output shared below). 

User request would be for individual pdfs of the different plots, but failing that would be for properly formatted full-page results.

[Blobulator.pdf](https://github.com/BranniganLab/blobulator/files/11524762/Blobulator.pdf)

**Comment by gbrannigan** [comment]
Plan:

- [ ] @cpitman-11 immediately change the button to read "Print Screen" so the user knows what to expect 
- [ ] @cpitman-11 @EzryStIago investigate why the side is getting cut off. I'm not worried about the slider since the number is still printed
- [ ] @cpitman-11 make an enhancement issue to implement proper downloading of plots. This was postponed a while ago as we were settling on the plots themselves but it seems the time is right
